import torch
from diffusion_graph import funcs
import operator

TYPE_MAP = {
    "f32": torch.float32,
    "i32" : torch.int32,
    "i64" : torch.int64,
    "i1" : torch.bool,
    "si64" : torch.int64,
    "diffusion_graph.str": str,
}

OP_MAP = {
    "diffusion_graph.torch.Relu": torch.nn.functional.relu,
    "diffusion_graph.torch.add": torch.add,
    "diffusion_graph.torch.transpose": torch.transpose,
    "diffusion_graph.torch.matmul": torch.matmul,
    "diffusion_graph.torch.softmax": torch.nn.functional.softmax,
    "diffusion_graph.torch.addmm": torch.addmm,
    "diffusion_graph.torch.view": torch.reshape,
    "diffusion_graph.torch.bmm" : torch.bmm,
    "diffusion_graph.torch.div.scalar": torch.div,
    "diffusion_graph.torch.layer_norm": torch.nn.functional.layer_norm,
    "diffusion_graph.torch.tanh": torch.tanh,
    "diffusion_graph.torch.mul": torch.mul,
    "diffusion_graph.torch.pow": torch.pow,
    "diffusion_graph.torch.embedding": torch.nn.functional.embedding,
    "diffusion_graph.torch.broadcast_to" : torch.broadcast_to,
    "diffusion_graph.torch.permute" : torch.permute,
    "diffusion_graph.torch.index_select" : torch.index_select,
    "diffusion_graph.torch.unsqueeze": torch.unsqueeze,
    "diffusion_graph.torch.squeeze": torch.squeeze,
    "diffusion_graph.torch.sub": torch.sub,
    "diffusion_graph.torch.where": torch.where,
    "diffusion_graph.torch.cast_dtype": funcs.cast_func,
    "diffusion_graph.torch.scaled_dot_product_attention": torch.nn.functional.scaled_dot_product_attention,
    "diffusion_graph.torch.ones": torch.ones,
    "diffusion_graph.torch.arange": torch.arange,
    "diffusion_graph.torch.size": funcs.size_func,
    "diffusion_graph.torch.conv2d": torch.nn.functional.conv2d,
    "diffusion_graph.torch.group_norm": torch.nn.functional.group_norm,
    "diffusion_graph.torch.silu": torch.nn.functional.silu,
    "diffusion_graph.torch.gelu": torch.nn.functional.gelu,
    "diffusion_graph.torch.split": torch.split,
    "diffusion_graph.indexAt": operator.getitem,
    "diffusion_graph.torch.exp": torch.exp,
    "diffusion_graph.torch.sin": torch.sin,
    "diffusion_graph.torch.cos": torch.cos,
    "diffusion_graph.torch.concatenate": torch.cat,
    "diffusion_graph.torch.upsample": torch.nn.functional.interpolate,
    "diffusion_graph.torch.sigmoid": torch.nn.functional.sigmoid,
    "diffusion_graph.torch.less_than": torch.lt,
    "diffusion_graph.torch.contiguous": funcs.get_contiguous,
    "diffusion_graph.torch.narrow": torch.narrow,
    "diffusion_graph.torch.pad": torch.nn.functional.pad
}