import torch
from vllm_graph import funcs
import operator

TYPE_MAP = {
    "f32": torch.float32,
    "i32" : torch.int32,
    "i64" : torch.int64,
    "i1" : torch.bool,
    "si64" : torch.int64,
    "vllm_graph.str": str,
}

OP_MAP = {
    "vllm_graph.vllm.Relu": torch.nn.functional.relu,
    "vllm_graph.vllm.add": torch.add,
    "vllm_graph.vllm.transpose": torch.transpose,
    "vllm_graph.vllm.matmul": torch.matmul,
    "vllm_graph.vllm.softmax": torch.nn.functional.softmax,
    "vllm_graph.vllm.addmm": torch.addmm,
    "vllm_graph.vllm.view": torch.reshape,
    "vllm_graph.vllm.bmm" : torch.bmm,
    "vllm_graph.vllm.div.scalar": torch.div,
    "vllm_graph.vllm.layer_norm": torch.nn.functional.layer_norm,
    "vllm_graph.vllm.tanh": torch.tanh,
    "vllm_graph.vllm.mul": torch.mul,
    "vllm_graph.vllm.pow": torch.pow,
    "vllm_graph.vllm.embedding": torch.nn.functional.embedding,
    "vllm_graph.vllm.broadcast_to" : torch.broadcast_to,
    "vllm_graph.vllm.permute" : torch.permute,
    "vllm_graph.vllm.index_select" : torch.index_select,
    "vllm_graph.vllm.unsqueeze": torch.unsqueeze,
    "vllm_graph.vllm.squeeze": torch.squeeze,
    "vllm_graph.vllm.sub": torch.sub,
    "vllm_graph.vllm.where": torch.where,
    "vllm_graph.vllm.cast_dtype": funcs.cast_func,
    "vllm_graph.vllm.scaled_dot_product_attention": torch.nn.functional.scaled_dot_product_attention,
    "vllm_graph.vllm.ones": torch.ones,
    "vllm_graph.vllm.arange": torch.arange,
    "vllm_graph.vllm.size": funcs.size_func,
    "vllm_graph.vllm.conv2d": torch.nn.functional.conv2d,
    "vllm_graph.vllm.group_norm": torch.nn.functional.group_norm,
    "vllm_graph.vllm.silu": torch.nn.functional.silu,
    "vllm_graph.vllm.gelu": torch.nn.functional.gelu,
    "vllm_graph.vllm.split": torch.split,
    "vllm_graph.indexAt": operator.getitem,
    "vllm_graph.vllm.exp": torch.exp,
    "vllm_graph.vllm.sin": torch.sin,
    "vllm_graph.vllm.cos": torch.cos,
    "vllm_graph.vllm.concatenate": torch.cat,
    "vllm_graph.vllm.upsample": torch.nn.functional.interpolate,
    "vllm_graph.vllm.sigmoid": torch.nn.functional.sigmoid,
    "vllm_graph.vllm.less_than": torch.lt,
    "vllm_graph.vllm.contiguous": funcs.get_contiguous,
    "vllm_graph.vllm.narrow": torch.narrow,
}