#!/bin/bash

COMMIT_ID="${COMMIT_ID:-d418a03e01e6a31b51b0c9dd42ba46da6c47f89d}"

build_llvm(){
    cd /llvm-build/llvm-project
    git pull
    git checkout $COMMIT_ID
    cmake -B build \
      -G Ninja \
      -DCMAKE_CXX_COMPILER=clang++ \
      -DCMAKE_C_COMPILER=clang \
      -DCMAKE_BUILD_TYPE=Release \
      -DLLVM_ENABLE_ASSERTIONS=ON \
      -DLLVM_ENABLE_PROJECTS=mlir \
      -DLLVM_TARGETS_TO_BUILD=host \
      -DCMAKE_C_COMPILER_LAUNCHER=ccache \
      -DCMAKE_CXX_COMPILER_LAUNCHER=ccache \
      -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
      llvm

    cmake --build build -j$(nproc)
    cd $HOME
}

build_compiler(){
    export LLVM_INSTALL_DIR=/llvm-build/llvm-project/build
    current_dir=$(pwd)
    cd $HOME/vllm-project/compiler
    cmake -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=Release \
          -DCMAKE_C_COMPILER=clang \
          -DPython3_EXECUTABLE=$(which python3) \
          -DCMAKE_PREFIX_PATH=build \
          -DPython3_FIND_VIRTUALENV=ONLY \
          -DCMAKE_CXX_COMPILER=clang++ \
          -DMLIR_DIR="$LLVM_INSTALL_DIR/lib/cmake/mlir/" \
          -DLLVM_DIR="$LLVM_INSTALL_DIR/lib/cmake/llvm/" \
          -DTORCH_MLIR_SOURCE_DIR=$HOME/vllm-project/external/torch-mlir \
          -DMLIR_ENABLE_BINDINGS_PYTHON=ON \
          -DLLVM_TARGETS_TO_BUILD=host \
          -DTORCH_MLIR_ENABLE_STABLEHLO=OFF \
          -DTORCH_MLIR_ENABLE_PYTORCH_EXTENSIONS=ON \
          -DTORCH_MLIR_ENABLE_JIT_IR_IMPORTER=ON \
          -DTORCH_MLIR_OUT_OF_TREE_BUILD=ON \
          -DPYBIND11_PATH=$(python3 -c 'import pybind11; print(pybind11.__path__[0])')/share/cmake \
          .
    
    cmake --build build -j$(nproc)
    cd $current_dir
}

clean_compiler(){
    cd $HOME
    rm -rf $HOME/vllm-project/compiler/build
}